# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
cask "mac-ogcs" do
  require_relative "../lib/mac_ogcs_private_repository_release_download_strategy"

  version "0.2.2"

  on_macos do
    on_arm do
      sha256 "aa584151bdbf7d0a41072aa8e50c85ce56abd7d2cc0319b62b5aa3897dabc691"
      url "https://github.com/T-Py-T/mac-ogcs/releases/download/v#{version}/mac-ogcs_#{version}_darwin_arm64.zip",
          verified: "github.com/T-Py-T/mac-ogcs/",
          using:    MacOgcsPrivateRepositoryReleaseDownloadStrategy
    end
    on_intel do
      sha256 "3d0fd14bd6b4d9cbad09c15d0451146edfc80ba40a177eaf461662bcae4871b2"
      url "https://github.com/T-Py-T/mac-ogcs/releases/download/v#{version}/mac-ogcs_#{version}_darwin_amd64.zip",
          verified: "github.com/T-Py-T/mac-ogcs/",
          using:    MacOgcsPrivateRepositoryReleaseDownloadStrategy
    end
  end

  name "mac-ogcs"
  desc "Privacy-first Outlook-to-Google Calendar sync for terminals"
  homepage "https://github.com/T-Py-T/mac-ogcs"

  livecheck do
    skip "Auto-generated on release."
  end

  depends_on :macos

  binary "mac-ogcs"

  # No zap stanza required

  caveats <<~EOS
    This private release requires HOMEBREW_GITHUB_API_TOKEN when Homebrew
    downloads or upgrades it. Run `mac-ogcs`; press n to Sync now, r for a
    persistent recurring schedule, or g for Google source-calendar name and
    colour settings.

    The macOS binary is Developer ID signed with hardened runtime and its
    release ZIP is notarized by Apple. This Cask preserves normal macOS
    quarantine metadata and does not bypass Gatekeeper.
  EOS
end
